import rtconfig
from building import *

cwd     = GetCurrentDir()
#CPPPATH = [cwd, str(Dir('#'))]
#src     = Split("""
#main.c
#""")
src	= Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
